services:
  boilerplate:
    build:
      context: .
    container_name: boilerplate
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=Express-Sequelize-Boilerplate
      - SERVER_PORT=3000

      - MAIN_DB_HOST=postgres-boilerplate
      - MAIN_DB_PORT=5432
      - MAIN_DB_NAME=postgres
      - MAIN_DB_USERNAME=anbiasenggagau
      - MAIN_DB_PASSWORD=supersecret
      - MAIN_DB_ENGINE=postgres

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PORT=5672

      - REDIS_HOST=redis-boilerplate
      - REDIS_PORT=6379
      - REDIS_PASSWORD=supersecret

      - REFRESH_TOKEN=true
      - JWT_SECRET=supersecret
      - JWT_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=5d
      - NUMBER_OF_ALLOWED_SESSIONS=2
      - ENCRYPTION_SALT=10
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres-boilerplate
    environment:
      - POSTGRES_USER=anbiasenggagau
      - POSTGRES_PASSWORD=supersecret
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.4
    container_name: redis-boilerplate
    command: redis-server --requirepass supersecret
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq-boilerplate
    ports:
      - 5672:5672
      - 15672:15672