services:

  boilerplate:
    build:
      context: .
    container_name: boilerplate
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=Express-Sequelize-Boilerplate
      - SERVER_PORT=3000

      - MAIN_DB_HOST=postgres
      - MAIN_DB_PORT=5432
      - MAIN_DB_NAME=postgres
      - MAIN_DB_USERNAME=anbiasenggagau
      - MAIN_DB_PASSWORD=supersecret
      - MAIN_DB_ENGINE=postgres

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=supersecret

      - REFRESH_TOKEN=true
      - JWT_SECRET=supersecret
      - JWT_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=5d
      - NUMBER_OF_ALLOWED_SESSIONS=2
      - ENCRYPTION_SALT=10

  postgres:
    image: postgres:15.5
    container_name: postgres
    environment:
      - POSTGRES_USER=anbiasenggagau
      - POSTGRES_PASSWORD=supersecret
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.4
    container_name: redis
    command: redis-server --requirepass supersecret
    ports:
      - 6379:6379
