version: '3'
services:

  postgres:
    image: postgres:15.5
    container_name: postgres
    environment:
      - POSTGRES_USER=anbiasenggagau
      - POSTGRES_PASSWORD=supersecret
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.4
    container_name: redis
    command: redis-server --requirepass supersecret
    ports:
      - 6379:6379
