import { BelongsTo, Column, DataType, Model, Table } from "sequelize-typescript"
import Users from "./User"
import { Sequelize } from "sequelize"

export interface CustomerAttributes {
    id: number
    name: string
    address: string
    phoneNumber: string | null
    userId: string
    createdAt: Date
    createdBy: string
    updatedAt: Date
    updatedBy: string
    deletedAt: Date | null
    deletedBy: string | null
}

type CustomerAutoGeneratedAttributes = "id" | "createdAt" | "updatedAt" | "deletedAt"
type CustomerOptionalAttributes = "phoneNumber" | "createdBy" | "updatedBy" | "deletedBy"
export type CustomerCreationAttributes = Omit<CustomerAttributes, CustomerAutoGeneratedAttributes | CustomerOptionalAttributes> & Partial<Pick<CustomerAttributes, CustomerOptionalAttributes>>

@Table({
    freezeTableName: true,
    tableName: "customer",
    paranoid: true,
    underscored: true,
    schema: "public"
})
class Customer extends Model<CustomerAttributes | CustomerCreationAttributes> implements CustomerAttributes {
    @Column({
        allowNull: false,
        type: DataType.INTEGER,
        autoIncrement: true,
        primaryKey: true
    })
    id!: number

    @Column({
        allowNull: false,
        type: DataType.STRING(255)
    })
    name!: string

    @Column({
        allowNull: false,
        type: DataType.STRING(255)
    })
    address!: string

    @Column({
        allowNull: true,
        type: DataType.STRING(20)
    })
    phoneNumber!: string | null

    @Column({
        allowNull: false,
        type: DataType.UUID,
        unique: true
    })
    userId!: string

    @Column({
        allowNull: false,
        type: DataType.DATE,
        defaultValue: Sequelize.literal("now()")
    })
    createdAt!: Date

    @Column({
        allowNull: false,
        type: DataType.STRING(128),
        defaultValue: "System",
    })
    createdBy!: string

    @Column({
        allowNull: false,
        type: DataType.DATE,
        defaultValue: Sequelize.literal("now()")
    })
    updatedAt!: Date

    @Column({
        allowNull: false,
        type: DataType.STRING(128),
        defaultValue: "System",
    })
    updatedBy!: string

    @Column({
        allowNull: true,
        type: DataType.DATE
    })
    deletedAt!: Date | null

    @Column({
        allowNull: true,
        type: DataType.STRING(128)
    })
    deletedBy!: string | null

    @BelongsTo(() => Users, { foreignKey: "userId", targetKey: "id", onDelete: "CASCADE" })
    user!: Users
}

export default Customer
