import { BelongsTo, Column, DataType, Model, Table } from "sequelize-typescript"
import Stores from "./Store"
import { Sequelize } from "sequelize"

export interface ProductAttributes {
    id: number
    name: string
    price: number
    currency: string
    storeId: number
    createdAt: Date
    createdBy: string
    updatedAt: Date
    updatedBy: string
    deletedAt: Date | null
    deletedBy: string | null
}

type ProductAutoGeneratedAttributes = "id" | "createdAt" | "updatedAt" | "deletedAt"
type ProductOptionalAttributes = "createdBy" | "updatedBy" | "deletedBy"
export type ProductCreationAttributes = Omit<ProductAttributes, ProductAutoGeneratedAttributes | ProductOptionalAttributes> & Partial<Pick<ProductAttributes, ProductOptionalAttributes>>

@Table({
    freezeTableName: true,
    tableName: "product",
    paranoid: true,
    underscored: true,
    schema: "public"
})
class Product extends Model<ProductAttributes | ProductCreationAttributes> implements ProductAttributes {
    @Column({
        allowNull: false,
        type: DataType.INTEGER,
        autoIncrement: true,
        primaryKey: true
    })
    id!: number

    @Column({
        allowNull: false,
        type: DataType.STRING
    })
    name!: string

    @Column({
        allowNull: false,
        type: DataType.INTEGER
    })
    price!: number

    @Column({
        allowNull: false,
        type: DataType.STRING
    })
    currency!: string

    @Column({
        allowNull: false,
        type: DataType.INTEGER,
    })
    storeId!: number

    @Column({
        allowNull: false,
        type: DataType.DATE,
        defaultValue: Sequelize.literal("now()")
    })
    createdAt!: Date

    @Column({
        allowNull: false,
        type: DataType.STRING(128),
        defaultValue: "System",
    })
    createdBy!: string

    @Column({
        allowNull: false,
        type: DataType.DATE,
        defaultValue: Sequelize.literal("now()")
    })
    updatedAt!: Date

    @Column({
        allowNull: false,
        type: DataType.STRING(128),
        defaultValue: "System",
    })
    updatedBy!: string

    @Column({
        allowNull: true,
        type: DataType.DATE
    })
    deletedAt!: Date | null

    @Column({
        allowNull: true,
        type: DataType.STRING(128)
    })
    deletedBy!: string | null

    @BelongsTo(() => Stores, { foreignKey: "storeId", targetKey: "id", onDelete: "CASCADE" })
    store!: Stores
}

export default Product