import { BelongsTo, Column, DataType, HasMany, Model, Table } from "sequelize-typescript"
import Products from "./Product"
import Users from "./User"
import { Sequelize } from "sequelize"

export interface StoreAttributes {
    id: number
    name: string
    userId: string
    createdAt: Date
    updatedAt: Date
}

type StoreAutoGeneratedAttributes = "id" | "createdAt" | "updatedAt"
export type StoreCreationAttributes = Omit<StoreAttributes, StoreAutoGeneratedAttributes>

@Table({
    freezeTableName: true,
    tableName: "store",
    paranoid: false,
    underscored: true,
    schema: "public"
})
class Store extends Model<StoreAttributes | StoreCreationAttributes> implements StoreAttributes {
    @Column({
        allowNull: false,
        type: DataType.INTEGER,
        autoIncrement: true,
        primaryKey: true
    })
    id!: number

    @Column({
        allowNull: false,
        type: DataType.STRING
    })
    name!: string

    @Column({
        allowNull: false,
        type: DataType.UUID,
        unique: true,
    })
    userId!: string

    @Column({
        allowNull: false,
        type: DataType.DATE,
        defaultValue: Sequelize.literal("now()")
    })
    createdAt!: Date

    @Column({
        allowNull: false,
        type: DataType.DATE,
        defaultValue: Sequelize.literal("now()")
    })
    updatedAt!: Date

    @BelongsTo(() => Users, { foreignKey: "userId", targetKey: "id", onDelete: "CASCADE" })
    user!: Users

    @HasMany(() => Products, { foreignKey: "storeId", sourceKey: "id", onDelete: "CASCADE" })
    product!: Products[]
}

export default Store
